### ISSUE TITLE
do this have log to file or something thanks

### ISSUE THREAD

**Issue by hellok** [sarenji/pyrc#16]
~~rt

**Comment by wei2912** [comment]
You can redirect output from the bot to a log file in Linux using the following:

```
python example.py > log.txt
```

To append:

```
python example.py >> log.txt
```

I think there's no need for logging functionality as this would only clog up the library's code. The above is perfectly adequate :)

**Comment by sarenji** [comment]
Agreed. I'd prefer to use UNIX piping to redirect output. Feel free to discuss further, but closing now!
