### ISSUE TITLE
Add silent mode

### ISSUE THREAD

**Issue by evan** [sarenji/pyrc#7]
Always printing the received line makes it annoying to use as a library in some other program.

**Comment by sarenji** [comment]
Good idea. I'll add this by the end of this week.

**Comment by sarenji** [comment]
Let me know if the latest version of master works for you. You can add a `verbose=False` flag when initializing the bot and it'll squash all output.

**Comment by evan** [comment]
Works!

**Comment by sarenji** [comment]
Sweet.
